import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import UserContextProvider from "../../state/userProvider";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chess.com Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="Chess.com Clone: Play chess online with ease. Generated by create next app."
        />
        <meta
          name="keywords"
          content="chess, online chess, play chess, chess.com clone"
        />
        <meta name="author" content="Your Name" />
        <meta property="og:title" content="Chess.com Clone" />
        <meta
          property="og:description"
          content="Play chess online with ease. Generated by create next app."
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://yourwebsite.com" />
        <meta
          property="og:image"
          content="https://yourwebsite.com/og-image.jpg"
        />
        <meta property="og:site_name" content="Chess.com Clone" />
        <link rel="icon" href="/favicon.ico" />
        <title>Chess.com Clone</title>
      </Head>
      <body className={inter.className}>
        <UserContextProvider>
          <Toaster />
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
